### PR TITLE
Makefile and configuration

### PR DESCRIPTION
**Pull request by piotrplenik**
Simplify commands, by implementing global Configuration file and simple Makefiles for create/update stack, ECR login, ECR create nodes and update the desired count. 

And at least: updated: [Readme.md](https://github.com/jupeter/ecs-selenium/blob/402873229acfab8439f5e931df87dceb0e378030/README.md). 

Hope you enjoy, If you have any comments, please let me know.

### CODE REVIEW

**Comment by piotrplenik** [comment]
Hi @rrivera-rmn,
I see that my change works stable. 
Any comments/notices on my PR?

**Comment by rrivera-rmn** [comment]
@jupeter, found a make task that was misnamed. Other than that it looks good.

Thanks!

**Comment by piotrplenik** [comment]
@rrivera-rmn, thanks for a reply. 
Where exactly?

**Comment by rrivera-rmn** [comment]
@jupeter sorry. I could have sworn I made a comment inline, but it's not showing up:

```
# create the Firefox ECR repository
make ecr-create-firefox-node

# create the Chrome ECR repository
make ecr-create-firefox-node   # this should be chrome
```

**Comment by piotrplenik** [comment]
Thank you - now see. 
Updated!

**Review by rrivera-rmn — APPROVED** [review]

**Pull request merged**
