### PR TITLE
updating docs

### PR DESCRIPTION
**Pull request by elijahchancey**

### CODE REVIEW

**Comment by mwedgwood-rmn** [comment]
Hi, @elijahchancey. Thanks for the contribution!

It's definitely helpful to point out that the repo needs to be created. As this only needs to happen the first time, I think it's prudent to mention that detail in the comment just before the command. Would you mind updating your PR?

Thanks again.

**Comment by elijahchancey** [comment]
Do some of those steps need to happen more than beyond the first time?

**Comment by robertoriv** [comment]
> Do some of those steps need to happen more than beyond the first time?

The creation of the repo would only need to happen one time. But you could build new images, and push them to ECR, on a more frequent basis to get newer browsers in your cluster.

A note saying that the creation needs to happen only once sounds like a good idea.

Thanks!

**Comment by elijahchancey** [comment]
I made your change and also added a few more clarifications. Also, it's important to note that if you don't add the backslash escapes before the quotes when specifying subnet-ids, awscli will fail. it will error because it believes you're specifying a list of subnets instead of a string of comma delimited subnets.

**Review by robertoriv — APPROVED** [review]
👍 Looks good.

Thanks!

**Pull request merged**
